TaskManager/TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homePage, name="home"),
    path('accounts/', include('accounts.urls')),
    path('tasks/', include('tasks.urls')),
]

urlpatterns += staticfiles_urlpatterns()

TaskManager/accounts/urls.py
# current app handles user login, signup, logout and authentication part 

from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	
	path('signup/', views.signup_view, name='signup'),  # name = 'signup' => namespacing the url so that it can be used later on
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),

]

TaskManager/tasks/urls.py
from django.urls import path
from . import views

# The current app (tasks) handles all the request to url starting with /tasks




app_name = "tasks"

urlpatterns = [
    path('', views.team_list, name='teams'),
    path('create-team/', views.create_team, name="createteam"),  
    path('<int:gid>/', views.member_list, name="memberlist"),
    path('<int:gid>/add-user/', views.add_user, name="adduser"),
   	path('<int:gid>/add-user/<int:pid>/', views.added, name="added"),
   	path('add-task/', views.add_individual_task, name="indtask"),
   	path('view-task/<int:tid>/', views.task_detail, name="taskdetail"),
   	path('edit-task/<int:tid>/', views.edit_task, name='edittask'),
   	path('<int:gid>/add-task/', views.add_group_task, name="grptask"),
   	path('<int:gid>/view-task/<int:tid>/', views.group_task_detail, name="grptaskdetail"),
   	path('<int:gid>/edit-task/<int:tid>/', views.group_edit_task, name="grpedittask"),
   	path('<int:gid>/assign-task/<int:tid>/', views.group_assign_task, name='grpassntask'),
   	path('<int:gid>/assign-task/<int:tid>/<int:pid>/', views.group_task_assigned, name='grpassndtask'),
   	
]

TaskManager/templates/base_layout.html
{%load static from staticfiles%}

<!DOCTYPE html>
<html>
  <head>
  	<meta charset='utf-8'>
  	<link rel="stylesheet" href="{%static 'style.css'%}">
  </head>
  <body>
    <div class="fixed">
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a id="imglogo" href="{% url 'tasks:teams' %}"><img src="{% static 'logo.png' %}"/></a></li>
           <li>
            <form class="create-team" action="{% url 'tasks:createteam' %}" method='post'>
              {% csrf_token %}
              <button  type="submit">Create Team</button>
            </form>
          </li>
          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method='post'>
              {% csrf_token %}
              <button id="logoutId" type="submit">Logout</button>
            </form>
          </li>
          {% else %}
          <li>
            <a href="{% url 'accounts:login' %}"><button>Login</button></a>
          </li>
          <li>
            <a href="{% url 'accounts:signup' %}"><button>Signup</button></a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  	<div class='wrapper'>
  	  {% block content %}
  	  {% endblock %}
  	</div> 
  </body>
</html

TaskManager/templates/homepage.html
{%load static from staticfiles%}
<!DOCTYPE html>
<html>
  <head>
  	<style>
  	body{
  		margin: 0;
  	}
	#particles-js{ 
			position:absolute; 
			width: 100%; 
			height: 100%; 
			background-image: url("/static/home.jpg");
			margin:0; 
			background-position: center;
			background-size: cover;
		}
		#login
		{
		  border:none;
		  position: absolute;
		  top:20%;
		  /* font-family: 'Times New Roman', Times, serif; */
		  font-size:20px;
		  left:50px;
		  border-radius: 6px;
		  width:10%;
		  height: 8%;
		  color:white;
		  background-color:black;
		}
		#login:hover
		{
		  color: black;
		  background-color:white;
		  cursor: pointer;
		}
		#signup
		{
		  border:none;
		  position: absolute;
		  top:40%;
		  /* font-family: 'Times New Roman', Times, serif; */
		  font-size:20px;
		  left:50px;
		  border-radius: 6px;
		  width:10%;
		  height: 8%;
		  color:white;
		  background-color:black;
		}
		#signup:hover
		{
		  color: black;
		  background-color:white;
		  cursor: pointer;
		}
		.bg-text {
		  color: white;
		  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
		 	
		  background-color: rgb(0,0,0); /* Fallback color */
		  background-color: rgba(0,0,0, 0.4); /* Black w/opacity/see-through */
		  border: 1px solid black;
		  position: absolute;
		  top: 300px;
		  left: 50%;
		  transform: translate(-50%, -50%);
		  z-index: 2;
		  width: 40%;
		  padding: 20px;
		  text-align: center;
		  height: 40%;
			
  		}
  		.bg-text .inner-text{
  			text-align: left;
  			margin-left: 100px;
  		}
  		.bg-text .madeby{
  			position: absolute;
  			top: 500px;
  			right: -250px;
  		}

  		
	</style>
  </head>

  <body>
    <div id="particles-js"></div>
    <a href="{% url 'accounts:login' %}"><button id="login">LOGIN</button></a>
	<a href="{% url 'accounts:signup' %}"><button id="signup">SIGNUP</button></a>
	<div class="bg-text">
      <h1>TASK MANAGER APP</h1>
      <p>A task manager app to make you manage tasks efficiently without any fuss</p>
      <br>
	  <p>Includes features like</p>
	  <div class="inner-text">
	      <ul>
	      	<li>Adding and editing task</li>
	      	<li>Creating groups and adding members to it</li>
	      	<li>Adding your personal comments on a task</li>
	      	<li>Assigning tasks to your group members</li>
	      </ul>
     </div>
     <div class="madeby">
	  <p style="font-size: 20px;">Developed by</p>
	  <p>Yogesh Choubey</p>
	  <p>NITK Surathkal</p>
	</div>
    </div>
	
  </body>
  <script src="{% static 'particles.js' %}"></script> 	
  <script src="{% static 'particlesjs-config.js' %}"></script>
</html>