TaskManager/TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homePage, name="home"),
    path('accounts/', include('accounts.urls')),
    path('tasks/', include('tasks.urls')),
]

urlpatterns += staticfiles_urlpatterns()

TaskManager/tasks/urls.py
from django.urls import path
from . import views

# The current app (tasks) handles all the request to url starting with /tasks




app_name = "tasks"

urlpatterns = [
    path('', views.team_list, name='teams'),
    path('create-team/', views.create_team, name="createteam"),  
    path('<int:gid>/', views.member_list, name="memberlist"),
    path('<int:gid>/add-user/', views.add_user, name="adduser"),
   	path('<int:gid>/add-user/<int:pid>/', views.added, name="added"),
   	path('add-task/', views.add_individual_task, name="indtask"),
   	path('view-task/<int:tid>/', views.task_detail, name="taskdetail"),
   	path('edit-task/<int:tid>/', views.edit_task, name='edittask'),
   	path('<int:gid>/add-task/', views.add_group_task, name="grptask"),
   	path('<int:gid>/view-task/<int:tid>/', views.group_task_detail, name="grptaskdetail"),
   	path('<int:gid>/edit-task/<int:tid>/', views.group_edit_task, name="grpedittask"),
   	path('<int:gid>/assign-task/<int:tid>/', views.group_assign_task, name='grpassntask'),
   	path('<int:gid>/assign-task/<int:tid>/<int:pid>/', views.group_task_assigned, name='grpassndtask'),
   	
]

TaskManager/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS_CHOICES = (('Planned', 'Planned'), ('Inprogress', 'Inprogress'), ('Done', 'Done'))  

# below model defines a group containing username of the group creator
class Group(models.Model):
	creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


# below model creates a many to many relationship between user and team (or group) 
class JoinTable(models.Model):
	person_id = models.ForeignKey(User, on_delete=models.CASCADE)
	group_id = models.ForeignKey(Group, on_delete=models.CASCADE)


# below model defines property of a task
class Task(models.Model):
	title = models.CharField(max_length=100)
	description = models.CharField(max_length=400)
	assignee = models.ForeignKey(User, on_delete=models.CASCADE)		# Creator of the task
	status = models.CharField(max_length=100, choices=STATUS_CHOICES)	# There are 3 choices for status
	group_id = models.ForeignKey(Group, on_delete=models.CASCADE, default=None, null=True)   # Set to -1 by default when a task doesn't belong to any group
	def __str__(self):
		return self.title

	def snippet(self):
		return self.description[:50] + '...'


# below model defines the property of a comment
class Comment(models.Model):
	task_id = models.ForeignKey(Task, on_delete=models.CASCADE)		# The id of the task to which the comment belongs to
	comment = models.CharField(max_length=300)
	commenter = models.ForeignKey(User, on_delete=models.CASCADE)
	

# below model defines the users assigned to a given task
class AssignTask(models.Model):
	task_id = models.ForeignKey(Task, on_delete=models.CASCADE)		
	person_id = models.ForeignKey(User, on_delete=models.CASCADE)

TaskManager/tasks/forms.py
from django import forms
from . import models


# Form for creating and editing a task
class CreateTask(forms.ModelForm):
	class Meta:
		model = models.Task
		fields = ['title', 'description', 'status']

TaskManager/tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from . import forms

# Current views handles all the requests related to tasks and teams
# @login_required used before every function to make sure that no unauthorized access takes place


# Handles the request for home page of the user
@login_required(login_url="/accounts/login")
def team_list(req):
	tasks = Task.objects.filter(group_id=None, assignee=req.user)

	# Quering for the list of groups the current user belongs to
	usergroups = JoinTable.objects.filter(person_id=req.user)
	group_id_list = []
	for group in usergroups:
		group_id_list.append(group.group_id.id)
	usergroups = Group.objects.filter(id__in=group_id_list)
	
	return render(req, 'tasks/teamlist.html', {'usergroups': usergroups, 'tasks':tasks})



# Handles the post request when a user creates a team
@login_required(login_url="/accounts/login")
def create_team(req):
	if req.method == 'POST':
		# Creates the group and saves it in the database
		newGroup = Group(creator=req.user)
		newGroup.save()
		newEntry = JoinTable(person_id=req.user, group_id=newGroup)
		newEntry.save()
		print('/tasks/' + str(newGroup.id) + '/')
		return render(req, 'tasks/memberlist.html', {'members': [req.user] ,'creator': req.user.username, 'groupid': newGroup.id, 'curruser': req.user.username, 'newTeam': 'yes'})




# Handles the request for the team page (the page containing the details of the respective team) of a user
@login_required(login_url="/accounts/login")
def member_list(req, gid):
	# Checking if the current user belongs to the group with group_id = gid
	group = Group.objects.filter(id=gid)
	if(group):
		group = group[0]
	else:
		group = None
	if JoinTable.objects.filter(group_id=group, person_id=req.user):
		# Quering for the list of users belonging to the current group
		memberIds = JoinTable.objects.filter(group_id=group)
		if memberIds:
			members = []
			for memberId in memberIds:
				members.append(User.objects.filter(id=memberId.person_id.id)[0].username)
			# Quering for the list of task belonging to the current group
			tasks = Task.objects.filter(group_id=group)
			return render(req, 'tasks/memberlist.html', {'members': members, 'creator': group.creator, 'groupid': group.id, 'curruser':req.user.username, 'tasks': tasks})
		else:
			return render(req, 'tasks/404.html')
	else:
		return render(req, 'tasks/404.html')



# Handles the request for the page containing the list of possible users that can be added to the current team 
@login_required(login_url="/accounts/login")
def add_user(req, gid):
	group = Group.objects.filter(id=gid)
	if(group):
		group = group[0]
	else:
		group = None
	if req.method == 'GET':
		# Checking if the current user belongs to the group with group_id = gid
		currmem = JoinTable.objects.filter(group_id=group)
		if currmem:
			# Quering for the list of possible users that can be added
			searchedgrp = group
			if req.user == searchedgrp.creator:
				arr = []
				for i in currmem:
					arr.append(i.person_id.id)
				nousers = User.objects.exclude(id__in=arr)
				return render(req, 'tasks/adduser.html', {'nousers': nousers, 'groupid': group.id})
			else:
				return render(req, 'tasks/404.html')
		else:
			return render(req, 'tasks/404.html')



# Handles the post request when a user tries to add another user to his team	
@login_required(login_url="/accounts/login")
def added(req, gid, pid):
	group = Group.objects.filter(id=gid)
	if(group):
		group = group[0]
	else:
		group = None
	if req.method == 'POST':
		# Saving the user to the database
		newEntry = JoinTable(person_id=User.objects.get(id=pid), group_id=group)
		newEntry.save()
		return redirect('/tasks/' + str(gid) + '/')




# Handles the post and get request for user adding individual task
@login_required(login_url="/accounts/login")
def add_individual_task(req):
	if req.method == 'POST':
		form = forms.CreateTask(req.POST)
		if form.is_valid():
			# save article to db
			instance = form.save(commit=False)
			instance.assignee = req.user
			instance.save()
			return redirect('tasks:teams')
	else:
		form = forms.CreateTask()
	return render(req, 'tasks/createtask.html', {'form': form})	




# Handles the request for page containing the details of individual tasks and also a post request for adding comment
@login_required(login_url="/accounts/login")
def task_detail(req, tid):
	task = Task.objects.filter(id=tid)
	if task and task[0].assignee == req.user:
		task = task[0]
		if req.method == 'GET':
			curr_user = req.user.username
			all_comments = Comment.objects.filter(task_id=task).order_by('-id')
			return render(req, 'tasks/taskdetail.html', {'task': task, 'curr_user': curr_user, 'all_comments': all_comments})
		else:
			newComment = Comment(task_id=tid, comment=req.POST.get('comment'), commenter=req.user.username)
			# Saving the comment to the db
			newComment.save()
			return redirect('/tasks/view-task/' + str(tid) + '/')

	else:
		return render(req, 'tasks/404.html')
	



# Handles the get and post request for user wanting to edit a task
@login_required(login_url="/accounts/login")
def edit_task(req, tid):
	task = Task.objects.filter(id=tid)
	if task:
		task = task[0]
		if task.assignee == req.user:
			if req.method == 'POST':
				form = forms.CreateTask(req.POST)
				if form.is_valid():
					# save the edited article to db
					instance = Task.objects.filter(id=tid)[0]
					instance.title = req.POST.get("title")
					instance.status = req.POST.get("status")
					instance.description = req.POST.get("description")
					instance.save()
					return redirect('tasks:teams')
			else:
				form = forms.CreateTask()
			return render(req, 'tasks/edittask.html', {'form': form, 'taskId': tid})
		else:
			return render(req, 'tasks/404.html')
	else:
		return render(req, 'tasks/404.html')



# Handles the request for a member belonging to a team and wanting to add a task in the team
@login_required(login_url="/accounts/login")
def add_group_task(req, gid):
	group = Group.objects.filter(id=gid)
	if(group):
		group = group[0]
	else:
		group = None
	curruser = JoinTable.objects.filter(group_id=group, person_id=req.user)
	# Checking if the current user belongs to the team
	if curruser:
		if req.method == 'POST':
			form = forms.CreateTask(req.POST)
			if form.is_valid():
				# saving article to db
				instance = form.save(commit=False)
				instance.assignee = req.user
				instance.group_id = group
				instance.save()
				return redirect('/tasks/' + str(gid) + '/')
		else:
			form = forms.CreateTask()
		return render(req, 'tasks/create_group_task.html', {'form': form, 'group_id': gid})

	else:
		return render(req, 'tasks/404.html')




# Handles the request for page containing the details of a task belonging to a particular team
@login_required(login_url="/accounts/login")
def group_task_detail(req, gid, tid):
	group = Group.objects.filter(id=gid)
	if(group):
		group = group[0]
	else:
		group = None
	task = Task.objects.filter(id=tid, group_id=group)
	curr = JoinTable.objects.filter(group_id=group, person_id=req.user)
	# Checking if the task and group exist and the task belongs to that group
	if task and curr:
		task = task[0]
		curr = curr[0]
		if req.method == 'GET':
			assigned_users = AssignTask.objects.filter(task_id=task)
			id_list = []
			for user in assigned_users:
				id_list.append(user.person_id.id)
			assigned_users = User.objects.filter(id__in=id_list)
			curr_user = req.user
			all_comments = Comment.objects.filter(task_id=task).order_by('-id')
			return render(req, 'tasks/group_task_detail.html', {'task': task, 'curr_user': curr_user, 'group_id':gid, 'task_id': tid, 'assigned_users': assigned_users, 'all_comments': all_comments})
		else:
			newComment = Comment(task_id=task, comment=req.POST.get('comment'), commenter=req.user)
			newComment.save()
			return redirect('/tasks/' + str(gid) + '/view-task/' + str(tid) + '/')
	else:
		return render(req, 'tasks/404.html')	




# Handles the request for a member belong to a team and wanting to edit a team task
@login_required(login_url="/accounts/login")
def group_edit_task(req, gid, tid):
	group = Group.objects.filter(id=gid)
	if(group):
		group = group[0]
	else:
		group = None
	task = Task.objects.filter(id=tid, group_id=group)
	# Checking if the task exists
	if task:
		task = task[0]
		if task.assignee == req.user:
			if req.method == 'POST':
				form = forms.CreateTask(req.POST)
				if form.is_valid():
					# saving the edited instance ot the article to db
					instance = Task.objects.filter(id=tid)[0]
					instance.title = req.POST.get("title")
					instance.status = req.POST.get("status")
					instance.description = req.POST.get("description")
					instance.save()
					return redirect('/tasks/' + str(gid) + '/')
			else:
				form = forms.CreateTask()
			return render(req, 'tasks/group_edit_task.html', {'form': form, 'task_id': tid, 'group_id': gid})
		else:
			return render(req, 'tasks/404.html')
	else:
		return render(req, 'tasks/404.html')	




# Handles the get request of a task creator wanting to assign a task to the members of the team
@login_required(login_url="/accounts/login")
def group_assign_task(req, gid, tid):
	group = Group.objects.filter(id=gid)
	if(group):
		group = group[0]
	else:
		group = None
	task = Task.objects.filter(id=tid, group_id=group)
	if task:
		task = task[0]
		# Checking if the current user is the creator of the task
		if task.assignee == req.user:
			already_assigned = AssignTask.objects.filter(task_id=task)
			assigned_id = []
			for person in already_assigned:
				assigned_id.append(person.person_id.id)	
			not_assigned_list = User.objects.exclude(id__in=assigned_id)
			not_assigned = JoinTable.objects.filter(person_id__in=not_assigned_list, group_id=group)
			temp_id = []
			for user in not_assigned:
				temp_id.append(user.person_id.id)

TaskManager/tasks/templates/tasks/adduser.html
{% extends 'base_layout.html' %}

{% block content %}
<!DOCTYPE html>
<html>
  <head>
  	<style>
  		.userlabel
  		{
  			left: 40%;
        position: absolute;
        float: left;
  			clear: both;
        padding-top: 10px;

  		}
  		.adduser
  		{
  			background: none;
        position: relative;
        left: 60%;
        cursor: pointer;
        border:1px solid #00dba0;
        padding: 10px;
        border-radius: 4px;
        color: #00dba0;
  	
  		}
  	</style>
  </head>
  <body>
  	<h1>User List</h1>
  	{%for nouser in nousers%}
  		<form action="{% url 'tasks:added' gid=groupid pid=nouser.id%}" method='post'>
	  		{% csrf_token %}
	  		<label class="userlabel">{{nouser.username}}</label>
	  		<button class="adduser" type="submit">ADD USER</button>
	  	</form>
      <br>
  	{%endfor%}
    {% if not nousers %}
    <h2 style="text-align: center;color: red">No one left to add</h2>
    {% endif %}
  </body>
</html>

{% endblock %}

TaskManager/tasks/templates/tasks/assign_user.html
{% extends 'base_layout.html' %}

{% block content %}
<!DOCTYPE html>
<html>
  <head>
  	<style>
  		.userlabel
      {
        left: 40%;
        position: absolute;
        float: left;
        clear: both;
        padding-top: 10px;

      }
      .adduser
      {
        background: none;
        position: relative;
        left: 60%;
        cursor: pointer;
        border:1px solid #00dba0;
        padding: 10px;
        border-radius: 4px;
        color: #00dba0;
    
      }
  	</style>
  </head>
  <body>
  	<h1>User List</h1>
  	{%for user in not_assigned%}
  		<form action="{% url 'tasks:grpassndtask' gid=group_id tid=task_id pid=user.id%}" method='post'>
	  		{% csrf_token %}
	  		<label class="userlabel">{{user.username}}</label>
	  		<button class="adduser" type="submit">ASSIGN USER</button>
	  	</form>
      <br>
  	{%endfor%}
    {% if not not_assigned %}
    <h2 style="text-align: center;color: red">No one left to assign</h2>
    {% endif %}

  </body>
</html>

{% endblock %}

TaskManager/tasks/templates/tasks/create_group_task.html
{% extends 'base_layout.html' %}

{% block content %}

  <div class='create_task'>
  	<h2>Create a new task</h2>
  	<form class='site-form' action="{% url 'tasks:grptask' gid=group_id %}" method="post">
  		{% csrf_token %}
  		{{form}}
  		<input type="submit" value="Create">
  	</form>
  </div>
  

{% endblock %}

TaskManager/tasks/templates/tasks/createtask.html
{% extends 'base_layout.html' %}

{% block content %}

  <div class='create_task'>
  	<h2>Create a new task</h2>
  	<form class='site-form' action="{% url 'tasks:indtask' %}" method="post">
  		{% csrf_token %}
  		{{form}}
  		<input type="submit" value="Create">
  	</form>
  </div>
  

{% endblock %}

TaskManager/tasks/templates/tasks/edittask.html
{% extends 'base_layout.html' %}

{% block content %}

  <div class='create_task'>
  	<h2>Edit the task</h2>
  	<form class='site-form' action="{% url 'tasks:edittask' tid=taskId %}" method="post">
  		{% csrf_token %}
  		{{form}}
  		<input type="submit" value="Edit">
  	</form>
  </div>
  

{% endblock %}

TaskManager/tasks/templates/tasks/group_edit_task.html
{% extends 'base_layout.html' %}

{% block content %}

  <div class='create_task'>
  	<h2>Edit the task</h2>
  	<form class='site-form' action="{% url 'tasks:grpedittask' tid=task_id  gid=group_id %}" method="post">
  		{% csrf_token %}
  		{{form}}
  		<input type="submit" value="Edit">
  	</form>
  </div>
  

{% endblock %}

TaskManager/tasks/templates/tasks/group_task_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class='task-detail'>
  <div class='task'>
  	<h1>{{task.title}}</h2>
  	<h2 class="status">{{task.status}}</h2>
  	<p>Created by: {{task.assignee}}</p>
  	<p>{{task.description}}</p>
  </div>
  {% if curr_user == task.assignee %}
  <nav style="margin-top: 40px;text-align: center;">
  	  <li><a id="edit" href="{% url 'tasks:grpedittask' gid=group_id tid=task_id%}">Edit</a></li>
      <li><a id="assign" href="{% url 'tasks:grpassntask' gid=group_id tid=task_id%}">Assign Task</a></li>
  </nav>
  {% endif %}
  <form style="margin: 30px 0 0 30px;" action="{% url 'tasks:grptaskdetail' gid=group_id tid=task_id %}" method='post'>
    {% csrf_token %}
    <textarea placeholder="Start a discussion..." style="opacity: 0.80; border: 1px solid #00dba0;border-radius: 10px;resize: none;padding: 10px 10px 10px 10px; font-size: 18px;" name="comment" rows="2" cols="40"></textarea>
    <br>
    <nav>
    <button style="margin-top: 10px;" type="submit">Comment</button>
    </nav>
  </form>
  <br>
   {% if all_comments %}
   <button id="btn" class="Clicked" style="background: none; color: white; border: 1px solid #00dba0;border-radius: 10px;font-size: 16px;cursor: pointer;padding: 5px; margin: 10px 10px 10px 10px;">View Comments</button>
   <div class="block" style="display: none; width:550px;margin-left: 40px;">
     {% for comment in all_comments %}
     <div style="padding:10px;border: 1px solid #00dba0;border-radius: 10px;">
       <p>{{comment.comment}}</p>
       <p style="color: #00dba0;position: relative; left: 400px;">{{comment.commenter}}</p>
     </div>
     {% endfor %}
   </div>
   {% endif %}
   {% if assigned_users %}
  <h1>Assigned Users</h1>
  <div class='tasks'>
  {%for user in assigned_users%}
      <div class='task'>
        <h2>{{user.username}}</h2>
      </div>
  {%endfor%}
  </div>
  {% endif %}
</div>
<script>
  st = document.getElementsByClassName('status');
  console.log(st); 
  for(i = 0;i < st.length;i++)
  {
      var color;
      if(st[i].innerText == 'Done')
        color = 'green';
      else if(st[i].innerText == 'Planned')
        color = 'red';
      else
        color = 'orange';
      st[i].style.color = color;
  }
  const titleinput = document.querySelector('textarea[name=comment]');
  console.log(titleinput)
  titleinput.addEventListener('keyup', (e) =>{
    titleinput.value = titleinput.value
                     .replace(/[\n\r]+/g, "")
                     .replace(/(.{60})/g, "$1\n");
  });
  btn = document.getElementById('btn');
  dis = document.getElementsByClassName('block')[0];
  btn.addEventListener('click', ()=>{
        if (btn.className == 'Clicked'){
            btn.className = 'NotClicked';
            dis.style.display = 'block';
        }
        else{
            btn.className = 'Clicked';
            dis.style.display = 'none';
        }
    
    });
</script>


{% endblock %}

TaskManager/tasks/templates/tasks/memberlist.html
{% extends 'base_layout.html' %}

{% block content %}
<!DOCTYPE html>
<html>
  <body>
    <nav id="userop">
  	<ul>
      {% if newTeam %}
      <p style="text-align: center; color: green; border: 1px solid green; border-radius: 10px;width: 500px; padding: 10px 10px 10px 10px;">Team Created Successfuly!!!</p>
      {% endif %}
  		{% if curruser == creator.username %}
  		<li><a id="addUser" href="{% url 'tasks:adduser' gid=groupid %}">Add User</a></li>
  		{% endif %}
      <li><a id="newTask" href="{% url 'tasks:grptask' gid=groupid %}">New Task</a></li>
  	</ul>
   </nav>
  	<h1>Creator: {{creator}}</h1>
    <h2>Team Members</h2>
    <br>
  	<div class='tasks'>
    {%for member in members%}
      <div class='task'>
        <h2>{{member}}</h2>
      </div>
    {%endfor%}
  </div> 
  {% if tasks %}
  <h1>Team Tasks</h1>
   <div class='tasks'>
    {%for task in tasks%}
      <div class='task'>
        <h2><a href="{% url 'tasks:grptaskdetail' gid=groupid tid=task.id%}">{{task.title}}</a></h2>
        <p>{{task.snippet}}</p>
        <p style="font-weight: bold;" class="status">{{task.status}}</p>
        <p class="author">added by {{task.assignee}}</p>
      </div>
    {%endfor%}
  </div>
  {% endif %}
  </body>
</html>
<script>
  st = document.getElementsByClassName('status');
  for(i = 0;i < st.length;i++)
  {
      var color;
      if(st[i].innerText == 'Done')
        color = 'green';
      else if(st[i].innerText == 'Planned')
        color = 'red';
      else
        color = 'orange';
      st[i].style.color = color;
  }
</script>

{% endblock %}

TaskManager/tasks/templates/tasks/taskdetail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class='task-detail'>
  <div class='task'>
  	<h1>{{task.title}}</h2>
  	<h2 class="status">{{task.status}}</h2>
  	<p>Created by: {{task.assignee}}</p>
  	<p>{{task.description}}</p>
  </div>
  <nav style="margin-top: 40px;text-align: center;">
  	  <a id="edit" href="{% url 'tasks:edittask' tid=task.id%}">Edit</a>
  </nav>
  <form style="margin: 30px 0 0 30px;" action="{% url 'tasks:taskdetail' tid=task.id %}" method='post'>
    {% csrf_token %}
    <textarea placeholder="Start a discussion..." style="opacity: 0.80; border: 1px solid #00dba0; border-radius: 10px;resize: none;padding: 10px 10px 10px 10px; font-size: 18px;" name="comment" rows="2" cols="40"></textarea>
    <br>
  <nav>
    <button style="margin-top: 10px;" type="submit">Comment</button>
  </nav>
  </form>
  <br>
   {% if all_comments %}
   <button id="btn" class="Clicked" style="background: none; color: white; border: 1px solid #00dba0;border-radius: 10px;font-size: 16px;cursor: pointer;padding: 5px; margin: 10px 10px 10px 10px;">View Comments</button>
   <div class="block" style="display: none; width:550px;margin-left: 40px;">
     {% for comment in all_comments %}
     <div style="padding:10px;border: 1px solid #00dba0;border-radius: 10px;">
       <p>{{comment.comment}}</p>
       <p style="color: #00dba0;position: relative; left: 400px;">{{comment.commenter}}</p>
     </div>
     {% endfor %}
   </div>
   {% endif %}
  <h1>Assigned Users</h1>
  <div class='tasks'>
    <div class='task'>
      <h2>{{curr_user}}</h2>
    </div>
  </div>
</div>
<script>

  st = document.getElementsByClassName('status');
  console.log(st); 
  for(i = 0;i < st.length;i++)
  {
      var color;
      if(st[i].innerText == 'Done')
        color = 'green';
      else if(st[i].innerText == 'Planned')
        color = 'red';
      else
        color = 'orange';
      st[i].style.color = color;
  }
  const titleinput = document.querySelector('textarea[name=comment]');
  titleinput.addEventListener('keyup', (e) =>{
    titleinput.value = titleinput.value
                     .replace(/[\n\r]+/g, "")
                     .replace(/(.{60})/g, "$1\n");
  });
  btn = document.getElementById('btn');
  dis = document.getElementsByClassName('block')[0];
  btn.addEventListener('click', ()=>{
        if (btn.className == 'Clicked'){
            btn.className = 'NotClicked';
            dis.style.display = 'block';
        }
        else{
            btn.className = 'Clicked';
            dis.style.display = 'none';
        }
    
    });
</script>
</div>



{% endblock %}

TaskManager/tasks/templates/tasks/teamlist.html
{% extends 'base_layout.html' %}

{% block content %}
  	<nav>
  		<ul>
  			<li><a id="newTask" href="{% url 'tasks:indtask' %}">New Task</a></li>
  		</ul>
  	</nav>
  	<h1 id="test">Your Tasks</h1>
   <div class='tasks'>
	  {%for task in tasks%}
	  	<div class='task'>
	  	  <h2><a href="{% url 'tasks:taskdetail' tid=task.id%}">{{task.title}}</a></h2>
	  	  <p>{{task.snippet}}</p>
	  	  <p style="font-weight: bold;" class="status">{{task.status}}</p>
	  	  <p class="author">added by {{task.assignee}}</p>
	  	</div>
	  {%endfor%}
	</div>
  	{% if usergroups %}
  	<h1>Your Teams</h1>
	<div class='tasks'>
	  {%for usergroup in usergroups%}
	  	<div class='task'>
	  	  <h2><a href="{% url 'tasks:memberlist' gid=usergroup.id %}">Team {{forloop.counter}}</a></h2>
	  	  <p class="author">created by {{usergroup.creator}}</p>
	  	</div>
	  {%endfor%}
	</div> 
	{% endif %}
<script>
  st = document.getElementsByClassName('status');	
  for(i = 0;i < st.length;i++)
  {
      var color;
      if(st[i].innerText == 'Done')
        color = 'green';
      else if(st[i].innerText == 'Planned')
        color = 'red';
      else
        color = 'orange';
      st[i].style.color = color;
  }
</script>


{% endblock %}